name: Harbour example test workflow

on: [push]

jobs:
  check-readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check the README for correct strings
      run: python tests/check_readme.py
